added express functionality
MaxaKozin/nodejs-homeworks pull request #2
Opened 2020-09-08 13:38 UTC by MaxaKozin

2020-09-08 14:24 UTC, odykyi commented on contacts.js
>  contactsPath = path.resolve(__dirname, "db", "contacts.json");
make contactsPath as const

2020-09-08 14:24 UTC, odykyi commented on contacts.js
> +  return (contacts = await fs.readFile(contactsPath, "utf-8"));
return await fs.readFile(contactsPath, "utf-8");

2020-09-08 14:25 UTC, odykyi requested changes
comments

2020-09-08 14:27 UTC, odykyi commented
@MaxaKozin wait for changes

2020-09-08 16:48 UTC, MaxaKozin commented on contacts.js
> +  return (contacts = await fs.readFile(contactsPath, "utf-8"));
Corrections done

2020-09-08 16:48 UTC, MaxaKozin commented on contacts.js
>  contactsPath = path.resolve(__dirname, "db", "contacts.json");
corrections done

2020-09-09 06:03 UTC, odykyi approved these changes

2020-09-09 06:03 UTC, merged